project_id = "vabvjbevziuceemtlxqj"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.process-email-queue]
    verify_jwt = true
  [functions.send-subscription-notification]
    verify_jwt = false
